### ISSUE TITLE
关于数据格式

### ISSUE THREAD

**Issue by simplify23** [bing1zhi2/chinese_ocr#1]
你好,可不可以给一下您这套代码的识别数据格式,训练的数据也是360万的那个数据集吗,还是自制了数据集,谢谢

**Comment by bing1zhi2** [comment]
是的,用那个就行,放train/images下,标签也放下面.我是想自制下,增加点能认识的字数,不过还没来得及,刚刚更新了readme说明这个问题了

**Comment by bing1zhi2** [comment]
数据格式已经写入README，另外也自己生成了一份数据集
