### ISSUE TITLE
模型效果

### ISSUE THREAD

**Issue by chen849157649** [bing1zhi2/chinese_ocr#3]
7476model 与 5990model的效果这两模型效果很差，与最后那个https://github.com/chineseocr/chineseocr项目的模型(ocr-lstm.pth)效果差很远，泛化能力差别忒大了，

**Comment by bing1zhi2** [comment]
这两个模型目前只能做为学习代码用。只用了生成的数据集，从头训练的，确实是泛化差，现在也没有时间调模型。我在readme上更新下说明吧。

**Comment by bing1zhi2** [comment]
我记得之前搞这个项目时，有测试过一些比较正和清的整张A4文字，效果还是可以的，手写体什么的就不用想了。训练集都没那么复杂。
